---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akuity.io
  resources:
  - namespaceclassbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akuity.io
  resources:
  - namespaceclassbindings/finalizers
  verbs:
  - update
- apiGroups:
  - akuity.io
  resources:
  - namespaceclassbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - akuity.io
  resources:
  - namespaceclasses
  verbs:
  - get
  - list
  - watch
